---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: testapp
        image: venpara/ven-app:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-password
                key: mysql_password
        ports:
        - containerPort: 8000
          name: flask-container
---
apiVersion: v1
kind: Service
metadata:
  name: testapp
  labels:
    app: flask
spec:
  ports:
  - port: 8000
    protocol: TCP
    name: flask
  selector:
    app: flask
  type: LoadBalancer
